package com.liferay.samples.services.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.samples.services.model.HelloSample;
import com.liferay.samples.services.service.HelloSampleService;
import com.liferay.samples.services.service.persistence.HelloSamplePersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the hello sample remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.samples.services.service.impl.HelloSampleServiceImpl}.
 * </p>
 *
 * @author Liferay
 * @see com.liferay.samples.services.service.impl.HelloSampleServiceImpl
 * @see com.liferay.samples.services.service.HelloSampleServiceUtil
 * @generated
 */
public abstract class HelloSampleServiceBaseImpl extends BaseServiceImpl
    implements HelloSampleService, IdentifiableBean {
    @BeanReference(type = com.liferay.samples.services.service.HelloSampleLocalService.class)
    protected com.liferay.samples.services.service.HelloSampleLocalService helloSampleLocalService;
    @BeanReference(type = com.liferay.samples.services.service.HelloSampleService.class)
    protected com.liferay.samples.services.service.HelloSampleService helloSampleService;
    @BeanReference(type = HelloSamplePersistence.class)
    protected HelloSamplePersistence helloSamplePersistence;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private HelloSampleServiceClpInvoker _clpInvoker = new HelloSampleServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.liferay.samples.services.service.HelloSampleServiceUtil} to access the hello sample remote service.
     */

    /**
     * Returns the hello sample local service.
     *
     * @return the hello sample local service
     */
    public com.liferay.samples.services.service.HelloSampleLocalService getHelloSampleLocalService() {
        return helloSampleLocalService;
    }

    /**
     * Sets the hello sample local service.
     *
     * @param helloSampleLocalService the hello sample local service
     */
    public void setHelloSampleLocalService(
        com.liferay.samples.services.service.HelloSampleLocalService helloSampleLocalService) {
        this.helloSampleLocalService = helloSampleLocalService;
    }

    /**
     * Returns the hello sample remote service.
     *
     * @return the hello sample remote service
     */
    public com.liferay.samples.services.service.HelloSampleService getHelloSampleService() {
        return helloSampleService;
    }

    /**
     * Sets the hello sample remote service.
     *
     * @param helloSampleService the hello sample remote service
     */
    public void setHelloSampleService(
        com.liferay.samples.services.service.HelloSampleService helloSampleService) {
        this.helloSampleService = helloSampleService;
    }

    /**
     * Returns the hello sample persistence.
     *
     * @return the hello sample persistence
     */
    public HelloSamplePersistence getHelloSamplePersistence() {
        return helloSamplePersistence;
    }

    /**
     * Sets the hello sample persistence.
     *
     * @param helloSamplePersistence the hello sample persistence
     */
    public void setHelloSamplePersistence(
        HelloSamplePersistence helloSamplePersistence) {
        this.helloSamplePersistence = helloSamplePersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();
    }

    public void destroy() {
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return HelloSample.class;
    }

    protected String getModelClassName() {
        return HelloSample.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = helloSamplePersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
