package com.liferay.samples.services.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.samples.services.model.HelloSample;
import com.liferay.samples.services.service.HelloSampleLocalServiceUtil;

/**
 * The extended model base implementation for the HelloSample service. Represents a row in the &quot;SAMPLES_HelloSample&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HelloSampleImpl}.
 * </p>
 *
 * @author Liferay
 * @see HelloSampleImpl
 * @see com.liferay.samples.services.model.HelloSample
 * @generated
 */
public abstract class HelloSampleBaseImpl extends HelloSampleModelImpl
    implements HelloSample {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a hello sample model instance should use the {@link HelloSample} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            HelloSampleLocalServiceUtil.addHelloSample(this);
        } else {
            HelloSampleLocalServiceUtil.updateHelloSample(this);
        }
    }
}
